//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomReservationService
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservation()
        {
            this.room_reservation = new HashSet<room_reservation>();
        }
    
        public string reservationId { get; set; }
        public Nullable<System.DateTime> reservationDate { get; set; }
        public Nullable<int> noOfAdults { get; set; }
        public Nullable<int> noOfChildren { get; set; }
        public Nullable<double> totalCost { get; set; }
        public string email { get; set; }
    
        public virtual reservation_user reservation_user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room_reservation> room_reservation { get; set; }
    }
}
